# **Student Name: Luja Ratna Manandhar**
# **Student ID: 2407087**

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:


import pandas as pd
data=pd.read_csv("/content/drive/MyDrive/Datasets/Data(Kaggle)/diabetes2.csv")
X=data.drop(columns=["BloodPressure"])
print(X.shape)


(768, 8)


In [17]:
y=data["BloodPressure"]
print(y.shape)

(768,)


In [18]:
n_class=2
filtered_data=data[data["BloodPressure"]<n_class]
X=filtered_data.drop(columns=["BloodPressure"])
y=filtered_data["BloodPressure"]
print(X.shape)
print(y.shape)

(35, 8)
(35,)


In [19]:
from sklearn.preprocessing import StandardScaler
data=[[0,0],[0,0],[1,1],[1,1]]
scaler=StandardScaler()
scaler.fit(data)
transformed_data=scaler.transform(data)
print(transformed_data)
transformed_data_direct=scaler.fit_transform(data)
print(transformed_data_direct)

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [20]:
from sklearn.model_selection import train_test_split

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,                      # Features and target variable
    test_size=0.25,            # Proportion of data to be used for testing (float between 0 and 1)
    train_size=None,           # Optional, can be set if test_size is None
    random_state=None,         # Seed for reproducibility
    shuffle=True,              # Shuffle the data before splitting
    stratify=None              # Maintain class distribution for classification tasks
)


In [21]:
from sklearn . model_selection import train_test_split
import numpy as np
# Example dataset
X = np . array ([[1 , 2] , [3 , 4] , [5 , 6] , [7 , 8] , [9 , 10]])
y = np . array ([0 , 1 , 0 , 1 , 0])
# Split the dataset (80% training , 20% testing )
X_train , X_test , y_train , y_test = train_test_split (X , y ,test_size =0.2 , random_state =42)
print (" X_train :", X_train )
print (" X_test :", X_test )
print (" y_train :", y_train )
print (" y_test :", y_test )

 X_train : [[ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
 X_test : [[3 4]]
 y_train : [0 0 0 1]
 y_test : [1]


In [22]:
class Estimator:
    def fit(self, X, y=None):
        """Fits estimator to data."""
        # Store the data to simulate learning
        self.X_ = X
        self.y_ = y
        return self

    def predict(self, X):
        """Makes predictions using the learned data."""
        # For this simple example, return the same values from the training data
        # In a real estimator, this would involve applying a trained model to the new data X
        if not hasattr(self, "X_"):
            raise ValueError("Model has not been fitted yet.")
        return self.y_  # Returning the stored labels for demonstration purposes


In [23]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the Iris dataset
data = load_iris()
X, y = data.data, data.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set hyper-parameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)

# Train the model using the training data
clf.fit(X_train, y_train)

# Make predictions on the first 5 samples from X
print("Predictions for the first 5 samples:", clf.predict(X[:5]))

# Compute class probabilities for the first 5 samples
print("Class probabilities for the first 5 samples:", clf.predict_proba(X[:5]))


Predictions for the first 5 samples: [0 0 0 0 0]
Class probabilities for the first 5 samples: [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [24]:
##Workshop questionssss


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df= pd.read_csv('/content/drive/MyDrive/Datasets/Data(Kaggle)/diabetes2.csv')
print("First 5 rows of the dataset:")
print(df.head())

print("\nData types of each column:")
print(df.dtypes)

print("\nMissing values in the dataset:")
print(df.isnull().sum())

print("\nSummary statistics:")
print(df.describe())


First 5 rows of the dataset:
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  

Data types of each column:
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    fl

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix, classification_report

X_reg = df.drop(columns=['BloodPressure', 'Outcome'])  # All columns except BloodPressure and Outcome
y_reg = df['BloodPressure']
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)
reg_model = LinearRegression()
reg_model.fit(X_train_reg, y_train_reg)

# Predict on test set
y_pred_reg = reg_model.predict(X_test_reg)

# Evaluate
print("Regression Evaluation:")
print(f"Mean Squared Error (MSE): {mean_squared_error(y_test_reg, y_pred_reg)}")
print(f"R^2 Score: {r2_score(y_test_reg, y_pred_reg)}")

Regression Evaluation:
Mean Squared Error (MSE): 408.8020357692283
R^2 Score: 0.182134664007779


In [26]:
X_clf = df.drop(columns=['Outcome'])
y_clf = df['Outcome']
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(X_clf, y_clf, test_size=0.2, random_state=42)
clf_model_logreg = LogisticRegression(max_iter=1000)
clf_model_logreg.fit(X_train_clf, y_train_clf)

y_pred_clf_logreg = clf_model_logreg.predict(X_test_clf)

# Evaluate
print("Logistic Regression Evaluation:")
print(f"Accuracy: {accuracy_score(y_test_clf, y_pred_clf_logreg)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test_clf, y_pred_clf_logreg)}")
print(f"Classification Report:\n{classification_report(y_test_clf, y_pred_clf_logreg)}")

Logistic Regression Evaluation:
Accuracy: 0.7467532467532467
Confusion Matrix:
[[78 21]
 [18 37]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154



In [27]:
clf_model_knn = KNeighborsClassifier(n_neighbors=5)
clf_model_knn.fit(X_train_clf, y_train_clf)

# Predict on test set
y_pred_clf_knn = clf_model_knn.predict(X_test_clf)

# Evaluate
print("KNN Evaluation:")
print(f"Accuracy: {accuracy_score(y_test_clf, y_pred_clf_knn)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test_clf, y_pred_clf_knn)}")
print(f"Classification Report:\n{classification_report(y_test_clf, y_pred_clf_knn)}")

KNN Evaluation:
Accuracy: 0.6623376623376623
Confusion Matrix:
[[70 29]
 [23 32]]
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.71      0.73        99
           1       0.52      0.58      0.55        55

    accuracy                           0.66       154
   macro avg       0.64      0.64      0.64       154
weighted avg       0.67      0.66      0.67       154

