# Student Name: Luja Ratna Manandhar
# Student Id: 2407087

# **3 Getting Started with Numpy.**
 This Section contains all the sample code from the slides and are here for your reference, you are highly
 recommended to run all the code with some of the input changed in order to understand the meaning of the operations and also to be able to solve all the exercises from further sections.


 **• Cautions!!!:–**

  This Guide does not contain sample output, as we expect you to re-write the code and observe
 the output.– If found: any error or bugs, please report to your instructor and Module leader.
 {Will hugely appreciate your effort.}

# 3.1 Array Introduction:
# 1. Importing Numpy:

 **Sample Code from Slide- 14- Importing Numpy and Array Type.**

In [ ]:
import numpy as np
 # Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



# 2. Array Dimensions: Shape and Resahpe of Array:
 **Sample Code from Slide- 16- Shape of an Array**

In [ ]:
import numpy as np
 # Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
 # Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
 print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



**Sample Code from Slide- 17- Reshaping an Array.**

In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


# 3.2 ArrayCreation:
# 1.UsingIn-BuiltFunction:

 Sample Code from Slide-18-Arrays with evenly Spaced values-arange.

In [ ]:
import numpy as np
a=np.arange(1, 10)
print(a)
x=range(1,10)
print(x)#xisan iterator
print(list(x))
#furtherarange examples:
x=np.arange(10.4)
print(x)
x=np.arange(0.5, 10.4,0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


**Sample Code from Slide-19-Arrays with evenly Spaced values- linspace.**

In [ ]:
import numpy as np
#50valuesbetween1and10:
print(np.linspace(1,10))
#7valuesbetween 1and10:
print(np.linspace(1,10,7))
#excludingtheendpoint:
print(np.linspace(1,10,7,endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


# 2. Initializing Arrays with Ones,Zeros and Empty:

 Sample Code form slide-20-Initializing an Array.

In [ ]:
import numpy as np
#Createarraysof specifiedshapes
ones_array=np.ones((2,3))#Shape:(2,3)
zeros_array=np.zeros((3,2))#Shape:(3,2)
empty_array=np.empty((2,2))#Shape:(2,2)
identity_matrix=np.eye(3)#Shape:(3,3)
print(ones_array,zeros_array,empty_array,identity_matrix,sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[5.06815564e-310 0.00000000e+000]
 [6.87613853e-310 6.87613853e-310]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 3. By Manipulating Existing Array:
# 3.1 Using np.array:

 Sample Code form slide-21-Converting list to array usingnp.array.

In [ ]:
import numpy as np
array_from_list=np.array([1,2,3])#[123]
array_from_tuple = np.array((4,5,6))#[456]
array_from_nested_list=np.array([[1,2,3],[4,5,6]])#[[123][456]]
print(array_from_list,array_from_tuple,array_from_nested_list,sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


# 3.2 Using shape of an existing array:

 Sample Code form slide-22-From shape of an existing array.

In [ ]:
import numpy as np
#ExistingArray ofShape:(2,3)
arr=np.array([[1,2,3],[4,5,6]])
#CreatingArray withShapeofexistingarray:
zeros, ones,empty =np.zeros(arr.shape),np.ones(arr.shape),np.empty(arr.shape)#Shape: (2,3)
print(arr,zeros,ones,empty,sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5.06815565e-310 0.00000000e+000 1.58101007e-322]
 [1.58101007e-322 1.23746313e-313 0.00000000e+000]]


# 3.3 With Math,Copying or Slicing and Array:
 **Sample Code form slide-23-Manipulatiing existing array.**

In [ ]:
import numpy as np
array=np.array([1,2,3])
#Multiplieseachelementby2,result:[2,4,6]
new_array=array*2
#Createsanewarraywiththesameelements
copied_array=np.copy(array)
#Sliceselementsfromindex1to3,result:[2]
sliced_array=array[1:2]

**Sample Code form slide-26-With Concatenating Operation.**

In [ ]:
import numpy as np
arr1= np.array([[1,2],[3,4]])#Shape:(2,2)
arr2= np.array([[5,6],[7,8]])#Shape:(2,2)
concat_axis0=np.concatenate((arr1,arr2),axis=0)
#Concatenatealongaxis0(vertical)Shape:(4,2)
concat_axis1=np.concatenate((arr1,arr2),axis=1)
#Concatenatealongaxis1(horizontal)Shape:(2,4)
print(concat_axis0,concat_axis1,sep='\n')

# 3.4 Array: Indexing and Slicing:
 **Sample Code form slide-34-Sample Code for Indexing and Slicing.**

In [ ]:
import numpy as np
#Arrays
arr1d=np.array([0,1,2,3,4,5])
arr2d=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr3d=np.array([[[0,1],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]]])
#Slicingexamples
print("Basic:",arr1d[1:4],arr2d[1:3,0:2],arr3d[1:2,0:2,1:2])
#OutputBasic:arr1d:[123]arr2d:[[34][67]]arr3d:[[[5][7]]]
print("Step:",arr1d[1:5:2],arr2d[::2,1::2],arr3d[::2,::2,1::2])
#Output:Step:[1 3][[1][7]][[[1][9]]]

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


# 3.3 Array Mathematics:
# 1.Elementary Mathematical Operation with universal functions.
 **Sample Code form slide-37-Intriduction to "ufuncs".**

In [ ]:
import numpy as np
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
print("Add:",np.add(arr1,arr2))#OutputAdd:[579]
print("Subtract:", np.subtract(arr1,arr2))
#OutputSubtract: [-3-3-3]
print("Divide:", np.divide(arr1,arr2))
#OutputDivide: [0.250.40.5]
print("Multiply:", np.multiply(arr1,arr2))
#OutputMultiply: [41018]
print("Power:",np.power(arr1,arr2))
#OutputPower:[132729]
print("Exp:",np.exp(arr1))
#OutputExp:[2.718281837.389056120.08553692]

Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


# 2.Matrix Multiplications.
 **Sample Code form slide-44-Using”np.dot”.**

In [ ]:
import numpy as np
#Definetwomatrices
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
#Matrixmultiplicationusingnp.dot
result_dot=np.dot(A,B)
print("Resultwith np.dot:\n",result_dot)#Outputshape:(2,2)

Resultwith np.dot:
 [[ 58  64]
 [139 154]]


**Sample Code form slide-45-Using "np.matmul"**

In [ ]:
import numpy as np
#Definetwomatrices
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
#Matrixmultiplicationusing@operator
result_at=A@B
print("Resultwith @operator:\n",result_at)#Outputshape:(2,2)
#Matrixmultiplicationusingnp.matmul
result_matmul=np.matmul(A,B)
print("Resultwith np.matmul:\n",result_matmul)#Outputshape:(2,2)

Resultwith @operator:
 [[ 58  64]
 [139 154]]
Resultwith np.matmul:
 [[ 58  64]
 [139 154]]


# 3.4 Linear Algebra with Numpy- np.linalg:
 **Sample Code form slide- 48- Common linear algebra operation with np.linalg.**

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5-0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant:-2.0
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Outptut: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A, B))
#Output: Solution x: [-4. 4.5]

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


# 4 TO-DO-Task
 **Please complete all the problem listed below.**

# 4.1 WarmingUpExercise: Basic Vector and Matrix Operation with Numpy.
 **Problem- 1: Array Creation:**
 Complete the following Tasks:

**1. Initialize an empty array with size 2X2.**

In [ ]:
import numpy as np
empty_array = np.empty((2,2))
print(empty_array)

[[1. 2.]
 [3. 4.]]


 **2. Initialize an all one array with size 4X2.**

In [ ]:
import numpy as np
array = np.ones((4, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}**

In [ ]:
import numpy as np
filled_array = np.full((2,2), 5)
print(filled_array)


[[5 5]
 [5 5]]


**4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}**

In [ ]:
import numpy as np
def zeros_array(arr):
  return np.zeros_like(arr)


arr = np.array([[1,2,3],[4,5,6]])
zeros_array = zeros_array(arr)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


 **5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}**

In [ ]:
import numpy as np
def ones_like(arr):
  return np.ones_like(arr)

arr= np.array([[4,5,6],[1,2,3]])
new_arr = ones_like(arr)
print(new_arr)

[[1 1 1]
 [1 1 1]]


**6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}**

In [ ]:
import numpy as np

new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


# 4.1.1 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:


 **1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.**

In [ ]:
import numpy as np

range_array = np.arange(10,50)
print(range_array)

 **2. Create a 3X3 matrix with values ranging from 0 to 8.**
 **{Hint:look for np.reshape()}**  

In [ ]:
import numpy as np
matrix = np.arange(9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. Create a 3X3 identity matrix.{Hint:np.eye()}**

In [ ]:
import numpy as np

new_identity_matrix = np.eye(3)
print(new_identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 **4. Create a random array of size 30 and find the mean of the array.**
 **{Hint:check for np.random.random() and array.mean() function}**

In [ ]:
import numpy as np

random_array = np.random.random(30)
mean_of_array = random_array.mean()
print(mean_of_array)

0.4445632642252452


**5. Create a 10X10 array with random values and find the minimum and maximum values.**

In [ ]:
import numpy as np

random_array = np.random.random(100).reshape((10,10))
max_val = random_array.max()
min_val = random_array.min()
print(random_array)
print(max_val)
print(min_val)

[[0.88382175 0.7271266  0.71933167 0.63793999 0.34721681 0.25852834
  0.44718423 0.50938761 0.01887297 0.51031242]
 [0.33327982 0.87456863 0.44567977 0.44622193 0.93456264 0.41206877
  0.67085247 0.95276657 0.42376797 0.37911331]
 [0.67941693 0.45995853 0.44694819 0.88644207 0.86364527 0.37169179
  0.12058901 0.36241145 0.03231817 0.33823687]
 [0.55263351 0.37330341 0.04186162 0.94069037 0.92593824 0.37324889
  0.77697343 0.23782289 0.89192843 0.13711921]
 [0.1139798  0.11261002 0.58827593 0.25363934 0.10475633 0.00836984
  0.66135011 0.05450444 0.66049903 0.96536953]
 [0.75802358 0.55283433 0.35513352 0.38399579 0.86314706 0.13437629
  0.09634995 0.34310824 0.69453158 0.40401656]
 [0.35709066 0.74115588 0.09202158 0.34540249 0.51417769 0.62712446
  0.91416569 0.5785568  0.40556321 0.21182841]
 [0.25393165 0.67961282 0.54318464 0.04250245 0.50458016 0.84177713
  0.44745169 0.62441002 0.28626725 0.4534911 ]
 [0.24087311 0.23471784 0.16839982 0.54823855 0.38666461 0.17883764
  0.91013366

 **6. Create a zero array of size 10 and replace 5th element with 1.**

In [ ]:
import numpy as np

zeros_array = np.zeros(10)
zeros_array[4] = 1
print(zeros_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 **7. Reverse an array arr = [1,2,0,0,4,0].**

In [ ]:
import numpy as np

arr = [1,2,0,0,4,0]
print("Orginal array: ",arr)
arr.reverse()
print("Reveresed array: ",arr)

Orginal array:  [1, 2, 0, 0, 4, 0]
Reveresed array:  [0, 4, 0, 0, 2, 1]


 **8. Create a 2d array with 1 on border and 0 inside.**

In [ ]:
import numpy as np

arr = np.zeros((5, 5))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print("2d array: \n",arr)

2d array: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


 **9. Create a 8X8 matrix and fill it with a checkerboard pattern.**

In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8))
checkerboard[::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
checkerboard[1::2, 1::2] = 0
print("Checkboard Pattern: \n",checkerboard)


Checkboard Pattern: 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# Problem- 3: Array Operations:
 For the following arrays:

 **x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);**

 **v = np.array([9,10]) and w = np.array([11,12]);**

 Complete all the task using numpy:

**1. Add the two array.**

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result = x + y

print("Array x:\n", x)
print("Array y:\n", y)
print("Sum of x and y:\n", result)

Array x:
 [[1 2]
 [3 5]]
Array y:
 [[5 6]
 [7 8]]
Sum of x and y:
 [[ 6  8]
 [10 13]]


**2. Subtract the two array.**

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

result = x - y

print("Array x:\n", x)
print("Array y:\n", y)
print("Difference of x and y:\n", result)

Array x:
 [[1 2]
 [3 5]]
Array y:
 [[5 6]
 [7 8]]
Difference of x and y:
 [[-4 -4]
 [-4 -3]]


**3. Multiply the array with any integers of your choice.**

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])

result = x * 3

print("Array x:\n", x)
print("Array x multiplied by 3:\n", result)

 **4. Find the square of each element of the array.**

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])

result = x ** 2

print("Array x:\n", x)
print("Square:\n", result)

Array x:
 [[1 2]
 [3 5]]
Square:
 [[ 1  4]
 [ 9 25]]


**5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.**

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:\n", dot_x_v)
print("Dot product of x and y:\n", dot_x_y)

**6. Concatenate x(and)y along row and Concatenate v(and)w along column.**

 {Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

xy_concatenated = np.concatenate((x, y), axis=0)

vw_concatenated = np.column_stack((v, w))

print("Concatenated x and y along row:")
print(xy_concatenated)

print("\nConcatenated v and w along column:")
print(vw_concatenated)


**7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?**

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

try:
    result = np.concatenate((x, v), axis=0)
    print("Concatenated x and v along row:")
    print(result)
except ValueError as e:
    print(f"Error: {e}")


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Error Explanation:

When using np.conctenate, the arrays must have the same dimensions along all axes except the axis being concatenated. Here, x has two dimensions, but v has only one, so their shapes are incompatible for concatenation.

# Problem- 4: Matrix Operations:

 • For the following arrays:

 **A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);**

 Prove following with Numpy:

 **1. Prove A.A−1 = I.**

 **2. Prove AB= BA.**

 **3. Prove (AB)T = BTAT.**

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Multiply A and A_inv
result = np.dot(A, A_inv)

# Identity matrix (2x2)
I = np.eye(2)

# Check result
print("A * A^-1:")
print(result)
print("\nIs A * A^-1 equal to I?", np.allclose(result, I))

A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A^-1 equal to I? True


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Print and compare
print("AB:")
print(AB)
print("\nBA:")
print(BA)
print("\nIs AB equal to BA?", np.array_equal(AB, BA))

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

Is AB equal to BA? False


In [ ]:
# Compute (AB)^T
AB_transpose = np.dot(A, B).T

# Compute B^T * A^T
BT_AT = np.dot(B.T, A.T)

# Print and compare
print("(AB)^T:")
print(AB_transpose)
print("\nB^T * A^T:")
print(BT_AT)
print("\nIs (AB)^T equal to B^T * A^T?", np.allclose(AB_transpose, BT_AT))


(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T * A^T? True


 **• Solve the following system of Linear equation using Inverse Methods.**

 2x −3y+z =−1

 x −y+2z =−3

 3x +y−z =9

 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

In [ ]:
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

# Display the solution
print("Solution (x, y, z):")
print(X)

Solution (x, y, z):
[ 2.  1. -2.]
